### ISSUE TITLE
AttributeError: 'NavigableString' object has no attribute 'name'

### ISSUE THREAD

**Issue by AhnSeongHyun** [AhnSeongHyun/slate-flask#23]
[ash84@webdev slate-flask]$ python slate.py
Traceback (most recent call last):
  File "slate.py", line 79, in <module>
    app.config['API_DOC_INDEX_PATH'])
  File "/home/ash84/slate-flask/api_document.py", line 20, in __init__
    self.contents = self.create_api_docs()
  File "/home/ash84/slate-flask/api_document.py", line 44, in create_api_docs
    docs[split(doc_file)[1]] = self.modify_html(self.highlight_syntax(self.reordering(html)))
  File "/home/ash84/slate-flask/api_document.py", line 54, in reordering
    if up_tag.name in ['pre', 'blockquote']:
  File "/usr/local/lib/python2.7/site-packages/bs4/element.py", line 667, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'NavigableString' object has no attribute 'name'
[ash84@webdev slate-flask]$

**Comment by AhnSeongHyun** [comment]
92363495f595afd15d356cef6f2fee7539b3a356
